CREATE TABLE Friend (idno NUMERIC(10),fname VARCHAR(24),address VARCHAR(30),age NUMERIC(10),giftvalue NUMERIC(10,2));
INSERT INTO Friend VALUES (1, 'Ram', 'Dwarka sector 10', 41, 200);
INSERT INTO Friend VALUES (2, 'Sita', 'Janakpuri block c', 26, 250);

SELECT * FROM Friend;
INSERT INTO friend  values ('03','Rajesh','Dwarka Sector 15','23','200');
INSERT INTO friend  values ('04','Ajit','Noida Sector 11','35','150');
INSERT INTO friend  values('05','Rita','Noida Sector 11','40','200');
SELECT * FROM Friend;
select*from friend where age>'40';
select Fname, Age from friend;
select Fname, Age, GiftValue from friend where Age>'35';
select*from friend where Giftvalue>'200'and Age>'20';
select * from friend where Giftvalue>'200' or Age>'20' ;
create table Employee(Empid numeric(10),Dept varchar(5),EmpName varchar(15),Adress varchar(30),salary numeric(7));
select*from employee;
insert into employee values ('101','RD01','Prince','Park Way','15000');
INSERT INTO Employee values('102','RD01', 'Harry', 'Pebble Street','12000');
INSERT INTO Employee values('103','RD02', 'Tom', 'Park Avenue','11000');
INSERT INTO Employee values('104','RD02', 'Susan', 'Model Town','10000');
INSERT INTO Employee values('105','ED01', 'Mark', 'Victor Crescent','10000');
INSERT INTO Employee values ('106','AD01', 'Francis', 'Chelmsford Park','13000');
INSERT INTO Employee values('107','GR01', 'Robert', 'Downtown Cross','14000');
INSERT INTO Employee values('108','RD03', 'Philip', 'Park Avenue','15000');
INSERT INTO Employee values('109','RD03','Henry', 'Malibu Beach','14000');
INSERT INTO Employee values('110','AD01','Frank', 'St. Peters Lane','7000');
select * from Employee;
select* from employee where Dept = 'RD01' ;
Select Empname, Dept, Salary from Employee;
Select Empname, Dept from Employee where Salary>'13000';
Select * from Employee where Adress = 'Park Avenue';
Select Empid, Empname from Employee where Salary='15000' and Adress='Park Avenue';
Select Empname from Employee where Dept='RD01';
Select * from Employee where Dept like 'RD%';
SELECT MAX(salary) FROM Employee;
SELECT MIN(salary) FROM Employee;
Select Empname, Dept from Employee where Salary>'12000';
UPDATE Employee SET Dept = 'AD01' Where EmpName = 'Susan';
select Empname from Employee where Dept='RD03' and Adress='Park Avenue';
select count(salary) from Employee;
select count(salary) from employee;
select * from Employee where salary>'12000';
create table FriendNew (Idno numeric(10) PRIMARY KEY, Fname varchar(24), Address varchar(30), Age numeric(10), Giftvalue Numeric(10,2));
INSERT INTO FriendNew values('01','Ram','Dwarka Sector 10','41','200');
INSERT INTO FriendNew values('02','Sita','Janakpuri Block c','26', '250.80');
INSERT INTO FriendNew values('03','Rajesh','Dwarka Sector 15','23','200');
INSERT INTO FriendNew values('04','Ajit','Noida Sector 11','35','150.50');
INSERT INTO FriendNew values('05','Rita','Noida Sector 11','40','200');
select* from friendnew;
select * from friendnew where Fname like'R%';
insert into friendnew values(123,'Anil','Dwarka Sector 11', 23, 29.99);
SET SQL_SAFE_UPDATES=0;
UPDATE friendnew SET Age ='28'where fname ='Sita';
delete FROM friendnew where Idno = '123';
UPDATE friendnew SET Giftvalue = '49.99' WHERE AGE = '31' OR AGE>'31';
alter Table friendnew add City varchar(15);
select* from friendnew;
select Fname, Age from friendnew order by Fname;
select sum(giftvalue) from friendnew;
select avg(Age) as 'Avrage Age' from friendnew;
select fname,age from friendnew where age =(select min(age)from friendnew);
Select Count(*)from FriendNew where Age>30;
select count(*) from friendnew where Giftvalue>30;
select fname,age from friendnew where age =(select max(age)from friendnew);
delete from friendnew where Idno = '123';
drop table friendnew;